### ISSUE TITLE
Incompatible with Sinytra Connector

### ISSUE THREAD

**Issue by marlester-dev** [BluSpring/Kilt#103]
### Version information

Kilt-0.0.1+mc1.20.1+build.e1ed31

### Expected Behavior

On Forge, the sinytra connector doesn't crash the game

### Actual Behavior

On Fabric with Kilt, the sinytra connector crashes the game

### Reproduction Steps

1. Install Kilt and its dependencies
2. Install Sinytra Connector and its dependencies
3. Start the game - BOOM, crash

### Java version

Java 17 (javaw)

### Log file

https://pastebin.com/uNfXvrRH

here is the error itself:
```java
[11:24:34] [main/ERROR]: Failed to load Forge mods in Kilt!
[11:24:34] [main/ERROR]: - Connector-1.0.0-beta.46+1.20.1.jar failed to load! Exception:
[11:24:34] [main/ERROR]: java.lang.NullPointerException: entry
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:363)
	at knot//xyz.bluspring.kilt.loader.KiltLoader.preloadJarMod(KiltLoader.kt:438)
	at knot//xyz.bluspring.kilt.loader.KiltLoader.preloadJarMod$default(KiltLoader.kt:356)
	at knot//xyz.bluspring.kilt.loader.KiltLoader.scanMods(KiltLoader.kt:86)
	at knot//xyz.bluspring.kilt.loader.KiltEarlierInitializer$onLanguageAdapterLaunch$1.invokeSuspend(KiltEarlierInitializer.kt:10)
	at knot//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at knot//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at knot//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at knot//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at knot//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at knot//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at knot//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at knot//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at knot//xyz.bluspring.kilt.loader.KiltEarlierInitializer.onLanguageAdapterLaunch(KiltEarlierInitializer.kt:10)
	at knot//de.florianmichael.asmfabricloader.api.EarlyRiser.invokeEntrypoints(EarlyRiser.java:49)
	at knot//de.florianmichael.asmfabricloader.AsmFabricLoader.<init>(AsmFabricLoader.java:51)
	at knot//de.florianmichael.asmfabricloader.AsmFabricLoader.install(AsmFabricLoader.java:47)
	at knot//de.florianmichael.asmfabricloader.loader.bootstrap.AFLLanguageAdapter.<clinit>(AFLLanguageAdapter.java:43)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:488)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:367)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:116)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
``` 

### Additional information

Mod list:
"Connector-1.0.0-beta.46+1.20.1.jar"
"Kilt-0.0.1+mc1.20.1+build.e1ed31.jar"
"sodium-fabric-0.5.11+mc1.20.1.jar"
"architectury-9.2.14-fabric.jar"
"fabric-api-0.92.2+1.11.8+1.20.1.jar" (forgified fabric api)
"fabric-api-0.92.2+1.20.1.jar" (normal fabric api)
"fabric-language-kotlin-1.13.0+kotlin.2.1.0.jar"
"ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric.jar"

**Comment by asoji** [comment]
what t he fucjk

**Comment by CephalonCosmic** [comment]
Intended functionality, but thank you for the issue anyways :)

**Comment by BluSpring** [comment]
I'm amazed you actually tried this and I applaud you for it, but also no.
