### ISSUE TITLE
curios api

### ISSUE THREAD

**Issue by siemxmods** [BluSpring/Kilt#111]
### Version information

5.11.0+1.20.1

### Reproduction Steps

1i open and it crashes

### Java version

java 8

### Crash Report file

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
	at knot//net.minecraftforge.registries.GameData.init(GameData.java:96)
	at knot//net.minecraftforge.registries.GameData.<clinit>(GameData.java:82)
	at knot//net.minecraft.class_7923.localvar$cab000$kilt$wrapWithGameDataWrapper(class_7923.java:523)
	at knot//net.minecraft.class_7923.method_47478(class_7923.java)
	at knot//net.minecraft.class_7923.method_47488(class_7923.java:209)
	at knot//net.minecraft.class_7923.method_47489(class_7923.java:197)
	at knot//net.minecraft.class_7923.<clinit>(class_7923.java:119)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:50)
	at knot//xyz.bluspring.kilt.loader.KiltLoader.initForge(KiltLoader.kt:941)
	at knot//xyz.bluspring.kilt.loader.KiltEarlyInitializer.onPreLaunch(KiltEarlyInitializer.kt:8)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 18 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [curios.mixins.json:AccessorEntity from mod curios] from phase [DEFAULT] in config [curios.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 21 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching firstTick:Z in net/minecraft/class_1297 for curios.mixins.json:AccessorEntity from mod curios->@Accessor[FIELD_GETTER]::getFirstTick()Z [ACCESSOR Applicator Phase -> curios.mixins.json:AccessorEntity from mod curios -> Apply Accessors ->  -> Locate -> curios.mixins.json:AccessorEntity from mod curios->@Accessor[FIELD_GETTER]::getFirstTick()Z]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1517)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:761)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 21 more

### Additional information

pls help

**Comment by Dettani** [comment]
I guess try accesories + curios compat layer for accesories

**Comment by Cartrigger** [comment]
Partially already tracked in #35 and your not using Java 8
