### ISSUE TITLE
Added mek mod crashes directly when opening the single-player button

### ISSUE THREAD

**Issue by QAQlinmiao** [BluSpring/Kilt#24]
### Version information

Kilt-0.0.1+mc1.20.1+build.6d0052

### Reproduction Steps

1.Add Mekanism mods and 215 commits kilt mods
2.Normally enter the main menu
3.Click the single player button and it crashes

### Java version

Java17

### Crash Report file

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-10-06 20:41:14
Description: mouseClicked event handler

java.lang.AbstractMethodError: Receiver class mekanism.common.item.loot.PersonalStorageContentsLootFunction$PersonalStorageLootFunctionSerializer does not define or inherit an implementation of the resolved method 'abstract java.lang.Object method_517(com.google.gson.JsonObject, com.google.gson.JsonDeserializationContext)' of interface net.minecraft.class_5335.
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1290)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.minecraft.class_3518.method_15291(class_3518.java:463)
	at net.minecraft.class_3518.method_15283(class_3518.java:481)
	at net.minecraft.class_85$class_90.method_441(class_85.java:149)
	at net.minecraft.class_85$class_90.method_424(class_85.java:129)
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86)
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74)
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1290)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.minecraft.class_3518.method_15291(class_3518.java:463)
	at net.minecraft.class_3518.method_15272(class_3518.java:471)
	at net.minecraft.class_55$class_57.method_358(class_55.java:173)
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1290)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.minecraft.class_3518.method_15291(class_3518.java:463)
	at net.minecraft.class_3518.method_15283(class_3518.java:481)
	at net.minecraft.class_52$class_54.method_340(class_52.java:250)
	at net.minecraft.class_52$class_54.deserialize(class_52.java:246)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1261)
	at net.minecraft.class_8490.method_51205(class_8490.java:64)
	at net.minecraft.class_8490.method_51204(class_8490.java:48)
	at net.minecraft.class_60.method_51195(class_60.java:55)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at net.minecraft.class_60.method_51189(class_60.java:55)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1290)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.minecraft.class_3518.method_15291(class_3518.java:463)
	at net.minecraft.class_3518.method_15283(class_3518.java:481)
	at net.minecraft.class_85$class_90.method_441(class_85.java:149)
	at net.minecraft.class_85$class_90.method_424(class_85.java:129)
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86)
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74)
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1290)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.minecraft.class_3518.method_15291(class_3518.java:463)
	at net.minecraft.class_3518.method_15272(class_3518.java:471)
	at net.minecraft.class_55$class_57.method_358(class_55.java:173)
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1319)
	at com.google.gson.Gson.fromJson(Gson.java:1290)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:412)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
	at oolloo.jlw.Wrapper.main(Wrapper.java:103)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.10, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 329314816 bytes (314 MiB) / 1073741824 bytes (1024 MiB) up to 7088373760 bytes (6760 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13500H
	Identifier: Intel64 Family 6 Model 186 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: OrayIddDriver Device
	Graphics card #0 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.1.58.818
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0xa7a0
	Graphics card #1 versionInfo: DriverVersion=32.0.101.5768
	Graphics card #2 name: NVIDIA GeForce RTX 4060 Laptop GPU
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x28a0
	Graphics card #2 versionInfo: DriverVersion=32.0.15.5599
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40424.49
	Virtual memory used (MB): 17653.38
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 82.39
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1013m -Xmx6758m
	Fabric Mods: 
		architectury: Architectury 9.2.14
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		forge: NeoForge 47.1.104
		forgeconfigapiport: Forge Config API Port 8.0.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kilt: Kilt 0.0.1+mc1.20.1+build.6d0052
			com_github_thecatcore_cursedmixinextensions: CursedMixinExtensions 1.1.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
			commons-codec_commons-codec: commons-codec 1.15
			cpw_mods_securejarhandler: securejarhandler 2.1.10
			dev_su5ed_sinytra_forgeautorenamingtool: ForgeAutoRenamingTool 1.0.9
			mixinsquared: MixinSquared 0.1.2-beta.5
			mm: Manningham Mills 2.3
			net_fabricmc_tiny-mappings-parser: tiny-mappings-parser 0.3.0+build.17
			net_jodah_typetools: typetools 0.8.3
			net_minecraftforge_eventbus: eventbus 6.2.4
			net_minecraftforge_forgespi: forgespi 7.1.3
			net_minecraftforge_mergetool-api: mergetool-api 1.0
			net_minecraftforge_srgutils: srgutils 0.4.13
			net_minecraftforge_unsafe: unsafe 0.2.0
			net_minecrell_terminalconsoleappender: terminalconsoleappender 1.3.0
			noindium: No Indium? 1.1.0+1.20
			org_apache_maven_maven-artifact: maven-artifact 3.8.5
			org_jline_jline-reader: jline-reader 3.12.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_asm: Porting Lib ASM 2.3.4+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.4+1.20.1
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
			porting_lib_gametest: Porting Lib GameTest 2.3.4+1.20.1
			porting_lib_gui_utils: Porting Lib Gui Utils 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_level_events: Porting Lib Level Events 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_model_builders: Porting Lib Model Builders 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			team_reborn_energy: Energy 3.0.0
		mekanism: Mekanism 10.4.9
		minecraft: Minecraft 1.20.1
	Launched Version: 1.20.1Kilt测试
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: 1883x959
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: zh_cn
	CPU: 16x 13th Gen Intel(R) Core(TM) i5-13500H

**Comment by BluSpring** [comment]
Known, see #20.

**Comment by QAQlinmiao** [comment]
I see, looking forward to the fix

**Comment by BluSpring** [comment]
Fixed in b1a0866725a203f3ba760a644278ca5303dfd519
