### ISSUE TITLE
Touhou Little Maid  crashing on start up

### ISSUE THREAD

**Issue by MineYF** [BluSpring/Kilt#33]
### Version information

Kilt-0.0.1+mc1.20.1+build.fed372

### Reproduction Steps

Kilt-0.0.1+mc1.20.1+build.fed372 and touhoulittlemaid-1.20.1-release-1.1.12-hotfix2

### Java version

Java 17 

### Crash Report file

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-10-10 03:40:44
Description: Initializing game

java.lang.RuntimeException
	at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:356)
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25)
	at xyz.bluspring.kilt.loader.KiltLoader$runPhaseExecutors$1.invoke(KiltLoader.kt:735)
	at xyz.bluspring.kilt.loader.KiltLoader$runPhaseExecutors$1.invoke(KiltLoader.kt:734)
	at xyz.bluspring.kilt.loader.KiltLoader.runPhaseExecutors$lambda$55(KiltLoader.kt:734)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at xyz.bluspring.kilt.loader.KiltLoader.runPhaseExecutors(KiltLoader.kt:734)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.kt:97)
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$2(ClientModLoader.java:67)
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:88)
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:67)
	at net.minecraft.class_310.handler$bnf000$kilt$initializeClientModLoader(class_310.java:3067)
	at net.minecraft.class_310.<init>(class_310.java:513)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
	at oolloo.jlw.Wrapper.main(Wrapper.java:103)
	Suppressed: java.lang.NullPointerException: Registry Object not present: touhou_little_maid:hakurei_gohei
		at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204)
		at com.github.tartaricacid.touhoulittlemaid.client.init.InitSpecialItemRender.register(InitSpecialItemRender.java:39)
		at com.github.tartaricacid.touhoulittlemaid.client.init.__InitSpecialItemRender_register_RegisterEvent.invoke(.dynamic)
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48)
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:290)
		at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.kt:40)
		at net.minecraftforge.fml.ModLoader.kiltPostEventWrappingMods(ModLoader.kt:46)
		at net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.kt:62)
		at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:375)
		... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:356)
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25)
	at xyz.bluspring.kilt.loader.KiltLoader$runPhaseExecutors$1.invoke(KiltLoader.kt:735)
	at xyz.bluspring.kilt.loader.KiltLoader$runPhaseExecutors$1.invoke(KiltLoader.kt:734)
	at xyz.bluspring.kilt.loader.KiltLoader.runPhaseExecutors$lambda$55(KiltLoader.kt:734)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at xyz.bluspring.kilt.loader.KiltLoader.runPhaseExecutors(KiltLoader.kt:734)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.kt:97)
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$2(ClientModLoader.java:67)
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:88)
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:67)
	at net.minecraft.class_310.handler$bnf000$kilt$initializeClientModLoader(class_310.java:3067)
	at net.minecraft.class_310.<init>(class_310.java:513)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:高级 Windows 32 基本 API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		AudioDevProps2.dll::2.6.14.0:A-Volute
		AudioDevProps2.dll::2.6.14.0:A-Volute
		COMCTL32.dll:用户体验控件库:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:加密 API32:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.4648 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.4355:Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.3636:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS 客户端 API DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL 实用工具库 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP 帮助程序 API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT 基本 API 客户端 DLL:10.0.19041.4842 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT 基本 API 客户端 DLL:10.0.19041.4842 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF 服务器 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.4123 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		NahimicOSD.dll:NahimicOSD:2.2.23.0:Nahimic
		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:用于 Windows 的 Microsoft OLE:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		PROPSYS.dll:Microsoft 属性系统:7.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows 性能数据助手 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		ProductInfo.dll
		RPCRT4.dll:远程过程调用运行时:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows 安装程序 API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell 公用 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:多用户 Windows 用户 API 客户端 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP 服务:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.19041.4780 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows 锁定策略:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows 加密基元库:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:用于 Windows 的 Microsoft COM:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		d3d9.dll:Direct3D 9 Runtime:10.0.19041.4842 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP 客户端服务:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 客户端:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft 桌面窗口管理器 API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec 用户模式 API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.4717 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.19041.4648 (WinBuild.160101.0800):Microsoft Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jna1830804729898180059.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.1.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation
		libjlw-x86_64-1.4.2.dll
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		mdnsNSP.dll:Bonjour Namespace Provider:3,1,0,1:Apple Inc.
		msasn1.dll:ASN.1 Runtime APIs:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mscms.dll:Microsoft 颜色匹配系统 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 服务提供程序:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:电子邮件命名填充提供程序:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt 路由器:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		ntdll.dll:NT 层 DLL:10.0.19041.4842 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA 提供程序:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		nvgpucomp64.dll:NVIDIA GPU Compiler Driver, Version 560.94 :32.0.15.6094:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:32.0.15.6094:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.28.0.417:NVIDIA Corporation
		opengl32.dll:OpenGL Client DLL:10.0.19041.4842 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows 系统性能对象 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP 命名空间提供程序:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:电源配置文件帮助程序 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:外壳简易实用工具库:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		svml.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.19041.4651 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme 库:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		win32u.dll:Win32u:10.0.19041.4894 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows 基本类型 DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft 公共控制器 API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
	at oolloo.jlw.Wrapper.main(Wrapper.java:103)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 320952064 bytes (306 MiB) / 1245708288 bytes (1188 MiB) up to 8266973184 bytes (7884 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: OrayIddDriver Device
	Graphics card #0 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.1.58.818
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x24c9
	Graphics card #1 versionInfo: DriverVersion=32.0.15.6094
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 55136.70
	Virtual memory used (MB): 23602.13
	Swap memory total (MB): 22528.00
	Swap memory used (MB): 3774.14
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1182m -Xmx7884m
	Fabric Mods: 
		architectury: Architectury 9.2.14
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.5
		forge: NeoForge 47.1.104
		forgeconfigapiport: Forge Config API Port 8.0.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kilt: Kilt 0.0.1+mc1.20.1+build.fed372
			com_github_thecatcore_cursedmixinextensions: CursedMixinExtensions 1.1.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
			commons-codec_commons-codec: commons-codec 1.15
			cpw_mods_securejarhandler: securejarhandler 2.1.10
			dev_su5ed_sinytra_forgeautorenamingtool: ForgeAutoRenamingTool 1.0.9
			mixinextras: MixinExtras 0.5.0-beta.3
			mixinsquared: MixinSquared 0.1.2-beta.5
			mm: Manningham Mills 2.3
			net_fabricmc_tiny-mappings-parser: tiny-mappings-parser 0.3.0+build.17
			net_jodah_typetools: typetools 0.8.3
			net_minecraftforge_eventbus: eventbus 6.2.4
			net_minecraftforge_forgespi: forgespi 7.1.3
			net_minecraftforge_mergetool-api: mergetool-api 1.0
			net_minecraftforge_srgutils: srgutils 0.4.13
			net_minecraftforge_unsafe: unsafe 0.2.0
			net_minecrell_terminalconsoleappender: terminalconsoleappender 1.3.0
			noindium: No Indium? 1.1.0+1.20
			org_apache_maven_maven-artifact: maven-artifact 3.8.5
			org_jline_jline-reader: jline-reader 3.12.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_asm: Porting Lib ASM 2.3.4+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.4+1.20.1
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
			porting_lib_gametest: Porting Lib GameTest 2.3.4+1.20.1
			porting_lib_gui_utils: Porting Lib Gui Utils 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_level_events: Porting Lib Level Events 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_model_builders: Porting Lib Model Builders 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			team_reborn_energy: Energy 3.0.0
		minecraft: Minecraft 1.20.1
		touhou_little_maid: Touhou Little Maid 1.1.12-hotfix2
	Launched Version: Fallcraft-beta
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz

**Comment by Cartrigger** [comment]
https://mclo.gs/0qNJ1fA
