### ISSUE TITLE
Pixelmon Reforged，TFC, AOA3 and AE2 crashes and won't start! Also a suggestion, can you update the NeoForge version from 47.1.103 to 47.1.106

### ISSUE THREAD

**Issue by Pokemon-Psyduck** [BluSpring/Kilt#39]
### Version information

Kilt 0.0.1build.90b178 + mc1.20.1

### Reproduction Steps

Install the mod and start Minecraft

### Java version

Zulu22.0.2

### Crash Report file

[latest.log](https://github.com/user-attachments/files/17479869/latest.log)

### Additional information

模组在启动时崩溃！ (A mod crashed on startup!)
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2966 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at xyz.bluspring.kilt.loader.KiltLoader.initForge(KiltLoader.kt:749)
	at xyz.bluspring.kilt.loader.KiltEarlyInitializer.onPreLaunch(KiltEarlyInitializer.kt:8)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method initRegistries(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in ae2.mixins.json:EarlyStartupMixin from mod ae2 failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap ae2.mixins.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more
![屏幕截图 2024-10-23 000711](https://github.com/user-attachments/assets/8f79a779-c1eb-40bb-90e2-e167a77d4e43)
![屏幕截图 2024-10-23 000733](https://github.com/user-attachments/assets/976360d7-f6db-4173-9e17-09158734a514)

**Comment by Project516** [comment]
This is still very early in development don’t expect to load up any mods especially huge ones and have them work

**Comment by Pokemon-Psyduck** [comment]
Any mod that modifies the biome system (world generator) won't work, and any mod that adds a new dimension won't work, please fix it soon!

**Comment by Pokemon-Psyduck** [comment]
> 这仍处于开发的早期阶段，不要指望加载任何 Mod，尤其是大型 Mod 并让它们工作

I am aware of this and I think that providing feedback for the Mod will help the author to refine this Mod, I think that this project of the author is very challenging and I like it very much, it allows me to load the Forge Mod in this Fabric and I am very much looking forward to how it will be used when it is in the future!

**Comment by Pokemon-Psyduck** [comment]
> This is still very early in development don’t expect to load up any mods especially huge ones and have them work

I know this, but this Mod I think is very necessary, I think providing feedback for the Mod will help the author to refine this Mod, I think this project by the author is very challenging and I like it very much, it allows me to load the Forge Mod in this Fabric, using Kilt on the Fabric to load both the Fabric and the Using Kilt on Fabric to load both Fabric and Forge Mod is still much faster than using Connector on Forge, this may be due to the light weight of Fabric, but such light weight also leads to the fact that BluSpring, the author of this mod, still can't load many mods for the World Generator after updating Kilt many times, but BluSping is very diligent in updating Kilt, I think BluSpring is a very good modifier. But BluSping is very diligent in updating the Kilt, I think BluSping's ability can make up for the shortcomings of the Fabric Loader, and I look forward to the future development of this mod and the large-scale integration packs of Fabric Mod and Forge Mod that are made with this mod, and the large-scale integration packs that are loaded with this mod will surely be able to enter the game very soon!

**Comment by BluSpring** [comment]
I forgot AE2 was accidentally broken at some point in fixing stuff, but I'm not actually sure what caused it to break.

**Comment by Cartrigger** [comment]
https://mclo.gs/IqkFNcW
Pixelmon Only

**Comment by Cartrigger** [comment]
![Image](https://github.com/user-attachments/assets/9fa65c53-2a27-47b9-93b0-83b64d705c61)

**Comment by Cartrigger** [comment]
https://mclo.gs/ToUf6Q4
