### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by Cherter821** [BluSpring/Kilt#41]
### Version information

Kilt-0.0.1+mc1.20.1+build.14df2a

### Reproduction Steps

1. Open Server
2. Crash

### Java version

Java 21

### Crash Report file

[20:11:12] [main/ERROR] [FabricLoader]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
	at com.mohistmc.banner.BannerMain.main(BannerMain.java:34) ~[server.jar:1.20.1-765]
	at com.mohistmc.banner.BannerLauncher.main(BannerLauncher.java:39) ~[server.jar:1.20.1-765]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.7.jar:?]
	... 5 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.world.item.ItemStack failed
	at net.minecraft.core.cauldron.CauldronInteraction.lambda$newInteractionMap$1(CauldronInteraction.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.Util.make(Util.java:436) ~[server-intermediary.jar:?]
	at net.minecraft.core.cauldron.CauldronInteraction.newInteractionMap(CauldronInteraction.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.core.cauldron.CauldronInteraction.<clinit>(CauldronInteraction.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.CauldronBlock.<init>(CauldronBlock.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:477) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:54) ~[server-intermediary.jar:?]
	at xyz.bluspring.kilt.loader.KiltLoader.initForge(KiltLoader.kt:758) ~[Kilt-0.0.1+mc1.20.1+build.14df2a.jar:?]
	at xyz.bluspring.kilt.loader.KiltEarlyInitializer.onPreLaunch(KiltEarlyInitializer.kt:8) ~[Kilt-0.0.1+mc1.20.1+build.14df2a.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.7.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.world.item.ItemStack failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.core.cauldron.CauldronInteraction.lambda$newInteractionMap$1(CauldronInteraction.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.Util.make(Util.java:436) ~[server-intermediary.jar:?]
	at net.minecraft.core.cauldron.CauldronInteraction.newInteractionMap(CauldronInteraction.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.core.cauldron.CauldronInteraction.<clinit>(CauldronInteraction.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.CauldronBlock.<init>(CauldronBlock.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:477) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:54) ~[server-intermediary.jar:?]
	at xyz.bluspring.kilt.loader.KiltLoader.initForge(KiltLoader.kt:758) ~[Kilt-0.0.1+mc1.20.1+build.14df2a.jar:?]
	at xyz.bluspring.kilt.loader.KiltEarlyInitializer.onPreLaunch(KiltEarlyInitializer.kt:8) ~[Kilt-0.0.1+mc1.20.1+build.14df2a.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.7.jar:?]
	... 5 more
Caused by: java.lang.NegativeArraySizeException: -1
	at org.objectweb.asm.Frame.merge(Frame.java:1233) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1612) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767) ~[asm-tree-9.7.1.jar:9.7.1]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647) ~[asm-tree-9.7.1.jar:9.7.1]
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:468) ~[asm-tree-9.7.1.jar:9.7.1]
	at org.spongepowered.asm.transformers.TreeTransformer.writeClass(TreeTransformer.java:82) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:235) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.3+mixin.0.8.7.jar:0.15.3+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.core.cauldron.CauldronInteraction.lambda$newInteractionMap$1(CauldronInteraction.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.Util.make(Util.java:436) ~[server-intermediary.jar:?]
	at net.minecraft.core.cauldron.CauldronInteraction.newInteractionMap(CauldronInteraction.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.core.cauldron.CauldronInteraction.<clinit>(CauldronInteraction.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.CauldronBlock.<init>(CauldronBlock.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:477) ~[server-intermediary.jar:?]
	at net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:54) ~[server-intermediary.jar:?]
	at xyz.bluspring.kilt.loader.KiltLoader.initForge(KiltLoader.kt:758) ~[Kilt-0.0.1+mc1.20.1+build.14df2a.jar:?]
	at xyz.bluspring.kilt.loader.KiltEarlyInitializer.onPreLaunch(KiltEarlyInitializer.kt:8) ~[Kilt-0.0.1+mc1.20.1+build.14df2a.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.7.jar:?]
	... 5 more

### Additional information

I uses Banner as my server

**Comment by Adidiii** [comment]
I'm not good at reading logs but... the bug seems Cauldron related? What Forge mods do you have installed, because the Banner server mod is a Fabric mod AFAIK. Maybe the Banner server mod and Kilt are incompatible?

**Comment by BluSpring** [comment]
It's likely an incompatibility between Banner and Kilt, considering Banner has a LOT of Minecraft mixins. There might be a way for me to mixin to Banner to fix compatibility though.

**Comment by Cherter821** [comment]
> It's likely an incompatibility between Banner and Kilt, considering Banner has a LOT of Minecraft mixins. There might be a way for me to mixin to Banner to fix compatibility though.

However, the server is still crash when i use Fabric (just Fabric server) ,reports below:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-10-24 20:41:04
Description: Exception in server tick loop

java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / forge:biome_modifier]
	at knot//net.minecraft.class_5455.method_30534(class_5455.java:26)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at knot//net.minecraft.class_5455.method_30530(class_5455.java:26)
	at knot//net.minecraftforge.server.ServerLifecycleHooks.runModifiers(ServerLifecycleHooks.java:219)
	at knot//net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:88)
	at knot//net.minecraft.class_3176.handler$zpp000$kilt$handleServerAboutToStart(class_3176.java:656)
	at knot//net.minecraft.class_3176.method_3823(class_3176.java:166)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 155575440 bytes (148 MiB) / 549453824 bytes (524 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 2
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5333
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32506.79
	Virtual memory used (MB): 7374.47
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx4G
	Fabric Mods: 
		architectury: Architectury 9.2.14
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
		forge: NeoForge 47.1.104
		forgeconfigapiport: Forge Config API Port 8.0.0
		java: OpenJDK 64-Bit Server VM 21
		kilt: Kilt 0.0.1+mc1.20.1+build.14df2a
			com_github_thecatcore_cursedmixinextensions: CursedMixinExtensions 1.1.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
			commons-codec_commons-codec: commons-codec 1.15
			cpw_mods_securejarhandler: securejarhandler 2.1.10
			dev_su5ed_sinytra_forgeautorenamingtool: ForgeAutoRenamingTool 1.0.9
			mixinextras: MixinExtras 0.5.0-beta.3
			mixinsquared: MixinSquared 0.2.0-beta.6
			mm: Manningham Mills 2.3
			net_fabricmc_tiny-mappings-parser: tiny-mappings-parser 0.3.0+build.17
			net_jodah_typetools: typetools 0.8.3
			net_minecraftforge_eventbus: eventbus 6.2.4
			net_minecraftforge_forgespi: forgespi 7.1.3
			net_minecraftforge_mergetool-api: mergetool-api 1.0
			net_minecraftforge_srgutils: srgutils 0.4.13
			net_minecraftforge_unsafe: unsafe 0.2.0
			net_minecrell_terminalconsoleappender: terminalconsoleappender 1.3.0
			org_apache_maven_maven-artifact: maven-artifact 3.8.5
			org_jline_jline-reader: jline-reader 3.12.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_asm: Porting Lib ASM 2.3.4+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.4+1.20.1
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
			porting_lib_gametest: Porting Lib GameTest 2.3.4+1.20.1
			porting_lib_gui_utils: Porting Lib Gui Utils 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_level_events: Porting Lib Level Events 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_model_builders: Porting Lib Model Builders 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			team_reborn_energy: Energy 3.0.0
		minecraft: Minecraft 1.20.1
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Cherter821** [comment]
With logs here: https://gist.github.com/Qha821-Happy/ce5eb54dc1f2269f319f57d05638d291
