### ISSUE TITLE
Game crashes on load with "OpenComputers II: Reimagined"

### ISSUE THREAD

**Issue by samuelh2005** [BluSpring/Kilt#43]
### Version information

Kilt-0.0.1+mc1.20.1+build.14df2a

### Reproduction Steps

1. Start the game
2. Game crashes before loading is finished

### Java version

`zulu17.52.17-ca-jre17.0.12-win_x64` (automatically choosen by the Modrinth App)

### Crash Report file

Lastest log: https://mclo.gs/5UkAHBA game crashes without a crash report.

The most important part of the log is:

```
[17:30:00] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//xyz.bluspring.kilt.loader.KiltLoader.initMod(KiltLoader.kt:631)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//xyz.bluspring.kilt.loader.KiltLoader.initMods(KiltLoader.kt:588)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//xyz.bluspring.kilt.Kilt$Companion.load(Kilt.kt:205)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.kt:72)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.client.loading.ClientModLoader.lambda$begin$2(ClientModLoader.java:67)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:88)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:67)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.handler$bnf000$kilt$initializeClientModLoader(class_310.java:3067)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.<init>(class_310.java:513)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.client.main.Main.main(Main.java:211)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17:30:00] [Render thread/INFO]: [STDERR]: Caused by: java.lang.IncompatibleClassChangeError: class li.cil.oc2r.common.entity.Robot overrides final method net.minecraft.class_1297.method_31745(Lnet/minecraft/class_1297$class_5529;)V
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//li.cil.oc2r.common.item.Items.<clinit>(Items.java:48)
[17:30:00] [Render thread/INFO]: [STDERR]: 	at knot//li.cil.oc2r.common.Main.<init>(Main.java:50)
[17:30:00] [Render thread/INFO]: [STDERR]: 	... 18 more
```

### Additional information

List of all mods:
- Architectury API `9.2.14` (Fabric) (required by Kilt)
- Architectury API `9.2.14` (Forge) (required by OC2R)
- Fabric API `0.92.2+1.20.1`(required by Kilt)
- Fabric Language Kotlin `1.12.3+kotlin.2.0.21` (required by Kilt)
- Forge Config API Port `v8.0.0-1.20.1-Fabric`(required by Kilt)
- Kilt `0.0.1+mc1.20.1+build.14df2a` (Fabric)
- Markdown Manual `MC1.20.1-forge-1.2.5` (required by OC2R)
- OpenComputers II: Reimagined `1.1.0+83b6d4e4` (Forge only)
- Sedna `1.0.30` (Forge only) (required by OC2R) (from https://github.com/Un1q32/sedna-mc)

https://github.com/North-Western-Development/oc2r/blob/1.20.1-1.1.0%2B83b6d4e4/src/main/java/li/cil/oc2r/common/entity/Robot.java is the code responsible from OC2R

**Comment by Cartrigger** [comment]
https://mclo.gs/7kzOY14

**Comment by Cartrigger** [comment]
it actually works

![Image](https://github.com/user-attachments/assets/8d8c7b4e-7e13-411c-bb40-eb4e38334807)
