### ISSUE TITLE
Difficult raids crashing on start up

### ISSUE THREAD

**Issue by Nokunami** [BluSpring/Kilt#7]
### Version information

difficultraids-1.19.2-2.0-beta.1

### Reproduction Steps

Example:
1. Drag & drop `difficultraids-1.19.2-2.0-beta.1.jar` into the mods folder
2. Launch the game
3. Crash

### Java version

Java 17.0.7

### Crash Report file

log:
```
[20:57:43] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.21
[20:57:45] [main/INFO]: Loading 103 mods:
	- architectury 6.5.85
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.6+kotlin.1.8.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- forgeconfigapiport 4.2.11
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- java 17
	- kilt 0.0.1.5+mc1.19.2
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	   |-- cpw_mods_securejarhandler 2.1.4
	   |-- forge_tags 3.0
	   |-- mm 2.3
	   |-- net_jodah_typetools 0.8.3
	   |-- net_minecraftforge_eventbus 6.0.4
	   |-- net_minecraftforge_forgespi 6.0.2
	   |-- net_minecraftforge_srgutils 0.4.13
	   |-- net_minecraftforge_unsafe 0.2.0
	   |-- net_minecrell_terminalconsoleappender 1.3.0
	   |-- noindium 1.1.0+1.19
	   |-- org_apache_maven_maven-artifact 3.8.5
	   |-- org_jline_jline-reader 3.12.1
	   |-- porting_lib_accessors 2.1.875+1.19.2
	   |-- porting_lib_attributes 2.1.875+1.19.2
	   |-- porting_lib_base 2.1.875+1.19.2
	   |    |-- mm 2.3
	   |    \-- porting_lib_loot 2.1.875+1.19.2
	   |-- porting_lib_common 2.1.875+1.19.2
	   |-- porting_lib_constants 2.1.875+1.19.2
	   |-- porting_lib_entity 2.1.875+1.19.2
	   |-- porting_lib_extensions 2.1.875+1.19.2
	   |-- porting_lib_fake_players 2.1.875+1.19.2
	   |-- porting_lib_lazy_registration 2.1.875+1.19.2
	   |-- porting_lib_model_generators 2.1.875+1.19.2
	   |-- porting_lib_model_loader 2.1.875+1.19.2
	   |-- porting_lib_models 2.1.875+1.19.2
	   |-- porting_lib_networking 2.1.875+1.19.2
	   |-- porting_lib_obj_loader 2.1.875+1.19.2
	   |-- porting_lib_transfer 2.1.875+1.19.2
	   |-- reach-entity-attributes 2.3.0
	   \-- serialization_hooks 0.3.26
	- lazydfu 0.1.3
	- minecraft 1.19.2
[20:57:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Users/User/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:57:47] [main/INFO]: Compatibility level set to JAVA_16
[20:57:47] [main/INFO]: Compatibility level set to JAVA_17
[20:57:51] [main/INFO]: Scanning the mods directory for Forge mods...
[20:57:51] [main/INFO]: Discovered Forge mod Difficult Raids (difficultraids) version 2.0-beta.1 (difficultraids-1.19.2-2.0-beta.1.jar)
[20:57:52] [main/INFO]: Found 1 Forge mods.
[20:57:52] [main/INFO]: Loading mappings from Searge to intermediary...
[20:57:52] [main/INFO]: Found cached mapping file
[20:57:52] [main/INFO]: Finished loading mappings! (took 252ms)
[20:57:52] [main/INFO]: Remapping Forge mods...
[20:57:52] [main/INFO]: Remapped Difficult Raids (difficultraids)
[20:57:52] [main/INFO]: Finished remapping mods!
[20:57:52] [main/INFO]: Modifying mods to workaround a classloading issue...
[20:57:52] [main/INFO]: Modifying Difficult Raids...
[20:57:52] [main/INFO]: Injected mod difficultraids into Fabric Loader
[20:57:53] [main/INFO]: Adding access transformers to mixin
[20:57:53] [main/INFO]: Finished loading access transformers (took 1ms)
[20:57:53] [main/INFO]: Starting initialization of Forge mods...
[20:57:53] [main/WARN]: Error loading class: tallestegg/guardvillagers/entities/Guard (java.lang.ClassNotFoundException: tallestegg/guardvillagers/entities/Guard)
[20:57:53] [main/WARN]: @Mixin target tallestegg.guardvillagers.entities.Guard was not found difficultraids.mixin.json:compat.GuardMixin from mod difficultraids
[20:57:53] [main/WARN]: Error loading class: baguchan/hunterillager/entity/HunterIllagerEntity (java.lang.ClassNotFoundException: baguchan/hunterillager/entity/HunterIllagerEntity)
[20:57:53] [main/WARN]: @Mixin target baguchan.hunterillager.entity.HunterIllagerEntity was not found difficultraids.mixin.json:compat.HunterIllagerMixin from mod difficultraids
[20:57:53] [main/WARN]: Error loading class: net/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoalnet/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoal (java.lang.ClassNotFoundException: net/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoalnet/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoal)
[20:57:53] [main/WARN]: @Mixin target net/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoalnet/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoal was not found difficultraids.mixin.json:illusioner.IllusionerBlindnessSpellGoalMixin from mod difficultraids
[20:57:53] [main/WARN]: Error loading class: net/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoalnet/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoal (java.lang.ClassNotFoundException: net/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoalnet/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoal)
[20:57:53] [main/WARN]: @Mixin target net/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoalnet/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoal was not found difficultraids.mixin.json:illusioner.IllusionerMirrorSpellGoalMixin from mod difficultraids
[20:57:55] [main/WARN]: Mixin kilt_forge_injects.mixins.json:world.level.block.LiquidBlockInject from mod kilt has multiple constructors, (Lnet/minecraft/class_4970$class_2251;)V was selected
[20:57:55] [main/WARN]: Method overwrite conflict for getFluid in architectury.mixins.json:LiquidBlockAccessor from mod architectury, previously written by xyz.bluspring.kilt.forgeinjects.world.level.block.LiquidBlockInject. Skipping method.
[20:57:55] [main/WARN]: Mixin kilt_forge_injects.mixins.json:world.level.block.PoweredRailBlockInject from mod kilt has multiple constructors, (ZLnet/minecraft/class_4970$class_2251;)V was selected
[20:57:55] [main/WARN]: Mixin kilt_forge_injects.mixins.json:world.level.block.PoweredRailBlockInject from mod kilt has multiple constructors, (ZLnet/minecraft/class_4970$class_2251;)V was selected
[20:57:58] [main/WARN]: Method overwrite conflict for deserializeNBT in kilt_forge_injects.mixins.json:world.item.ItemStackInject from mod kilt, previously written by io.github.fabricators_of_create.porting_lib.mixin.common.ItemStackMixin. Skipping method.
[20:57:58] [main/WARN]: Mixin kilt_forge_injects.mixins.json:world.item.ItemStackInject from mod kilt has multiple constructors, (Lnet/minecraft/class_1935;I)V was selected
[20:58:00] [main/INFO]: Building unoptimized datafixer
[20:58:04] [main/WARN]: Mixin kilt_forge_injects.mixins.json:world.item.CreativeModeTabInject from mod kilt has multiple constructors, (ILjava/lang/String;)V was selected
[20:58:06] [main/INFO]: Injected mod forge into Fabric Loader
[20:58:06] [main/WARN]: Mixin kilt_forge_injects.mixins.json:client.renderer.ShaderInstanceInject from mod kilt has multiple constructors, (Lnet/minecraft/class_5912;Ljava/lang/String;Lnet/minecraft/class_293;)V was selected
[20:58:06] [main/INFO]: Automatically registered event net.minecraftforge.client.ForgeHooksClientEvents from mod ID forge under bus MOD
[20:58:06] [main/INFO]: Automatically registered event net.minecraftforge.client.ClientForgeMod from mod ID forge under bus MOD
[20:58:06] [main/INFO]: Automatically registered event net.minecraftforge.common.ForgeSpawnEggItem$ColorRegisterHandler from mod ID forge under bus MOD
[20:58:06] [main/INFO]: Automatically registered event net.minecraftforge.client.model.data.ModelDataManager from mod ID forge under bus FORGE
[20:58:06] [main/INFO]: Automatically registered event net.minecraftforge.common.ForgeSpawnEggItem$CommonHandler from mod ID forge under bus MOD
[20:58:06] [main/INFO]: Forge mod loading, version 43.2.14, for MC 1.19.2 with MCP yarn
[20:58:06] [main/INFO]: MinecraftForge v43.2.14 Initialized
[20:58:07] [main/INFO]: Initialized new instance of mod forge.
[20:58:07] [main/INFO]: [STDOUT]: Scanning difficultraids_31_modified_6638524ea6e5ac6542c6ce2df37ff780.jar for mod initialization points...
[20:58:08] [main/INFO]: Automatically registered event com.calculusmaster.difficultraids.entity.DREntityEvents from mod ID difficultraids under bus FORGE
[20:58:08] [main/INFO]: Automatically registered event com.calculusmaster.difficultraids.events.DRForgeModEvents from mod ID difficultraids under bus FORGE
[20:58:08] [main/INFO]: Automatically registered event com.calculusmaster.difficultraids.events.DREntityRendererRegistry from mod ID difficultraids under bus MOD
[20:58:08] [main/WARN]: Mixin kilt_forge_injects.mixins.json:world.entity.ai.attributes.AttributeSupplierBuilderInject from mod kilt has multiple constructors, ()V was selected
[20:58:08] [main/INFO]: Automatically registered event com.calculusmaster.difficultraids.events.DREntityAttributeRegistry from mod ID difficultraids under bus MOD
[20:58:08] [main/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[20:58:08] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:58:08] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:58:08] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:58:08] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:58:08] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:58:08] [main/INFO]: [STDERR]: 	at xyz.bluspring.kilt.loader.KiltLoader.registerAnnotations(KiltLoader.kt:556)
[20:58:08] [main/INFO]: [STDERR]: 	at xyz.bluspring.kilt.loader.KiltLoader.loadMods(KiltLoader.kt:481)
[20:58:08] [main/INFO]: [STDERR]: 	at xyz.bluspring.kilt.loader.KiltEarlyInitializer.onPreLaunch(KiltEarlyInitializer.kt:8)
[20:58:08] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[20:58:08] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[20:58:08] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
[20:58:08] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
[20:58:08] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:58:08] [main/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: 'net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.method_29167()'
[20:58:08] [main/INFO]: [STDERR]: 	at com.calculusmaster.difficultraids.DifficultRaids.<init>(DifficultRaids.java:31)
[20:58:08] [main/INFO]: [STDERR]: 	... 13 more
```

**Comment by BluSpring** [comment]
oh dear god what happened here

**Comment by BluSpring** [comment]
okay, so.. this looks like an issue with the remapper.

which also makes me realize that I do not package optimized mappings for SRG -> Intermediary with Kilt.
Let me try reworking that code.

**Comment by BluSpring** [comment]
I think commit [d8a620b](https://github.com/KiltMC/Kilt/commit/d8a620b46c4b8326c8d48e5eb21e4b89b59257c8) just fixed it, do you mind checking to see if that build works?

**Comment by Nokunami** [comment]
d8a620b (Kilt-0.0.1.8+mc1.19.2) seems to crash as well
log: https://hastebin.com/share/lowixiwida.sql
As for Kilt 0.0.1.11 it crashed
log: https://hastebin.com/share/idewoniqiw.sql

**Comment by BluSpring** [comment]
The action is currently running, but can you try the latest build and see how that goes now?

this is precisely why i haven't released Kilt publicly on Modrinth, i expected these production crashes

**Comment by Nokunami** [comment]
0.0.1.12crashed,
log: https://hastebin.com/share/ikuwutocay.sql

**Comment by BluSpring** [comment]
okay, so at least i fixed that first issue, which is good.. I can look further into that next crash later. This one seems to be a different reason.

**Comment by Nokunami** [comment]
0.0.1.15 crashed,
log: https://hastebin.com/share/cimuxekupe.sql

**Comment by BluSpring** [comment]
expected it to still crash. I'll report back to you on when you can update again to test this. Right now I'm experiencing different problems in development after making my remapper changes.

**Comment by BluSpring** [comment]
GitHub why in the world did you autoclose it

Anyway @Nokunami can you try running 68b4f95?

**Comment by Nokunami** [comment]
0.0.1.23 crashed:
crash log: https://hastebin.com/share/vazuzopubi.yaml

**Comment by Nokunami** [comment]
0.0.1.26 loaded! gonna test the mod

**Comment by Nokunami** [comment]
ok so loading/creating a world works but rendering the mobs from difficult raids crashed the game,
crashlog: https://hastebin.com/share/etibaluqiw.yaml

**Comment by BluSpring** [comment]
Okay, a lot farther than before, I can look further into it next time I'm free

**Comment by Nokunami** [comment]
So i tested the latest build with different versions of difficult raids, 
this is for beta 1 [log](https://mclo.gs/zP2FCsC)
and this is for beta 11 [log](https://mclo.gs/B467Ld2)
beta 1 boots up but crashes at world creation, beta 11 crashes at start up.

**Comment by Nokunami** [comment]
I'm dumb, the mod was disabled on the beta 1 log
heres the actual [log](https://mclo.gs/CEhBcCU), it crashes on start up as well 😢

**Comment by BluSpring** [comment]
Kilt's latest build is currently unusable, I've been working on rewriting the remapper. Evidently it's not working too well.

**Comment by Cartrigger** [comment]
Difficult raids isn't on 1.20.1, so a close might be good
