### ISSUE TITLE
MineColonies crash

### ISSUE THREAD

**Issue by End198** [BluSpring/Kilt#70]
### Version information

minecolonies-1.20.1-1.1.700-snapshot

### Reproduction Steps

1. Install Minecolonies with its libs
2. Run Minecraft
3. Crash

### Java version

Java 17

### Crash Report file

[latest.log](https://github.com/user-attachments/files/17549417/latest.log)

### Additional information

Mod List:
![Screenshot 2024-10-28 182316](https://github.com/user-attachments/assets/cd7bfb7e-b170-4eee-834b-02bd72a737b2)
Also found error: [Render thread/ERROR] Detected config file conflict structurize between structurize and structurize

**Comment by samuelh2005** [comment]
Looks like an error with Structurize's config file (so not a MineColonies error):

```
[18:20:18] [Render thread/ERROR]: Detected config file conflict structurize between structurize and structurize
[18:20:18] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[18:20:18] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//xyz.bluspring.kilt.loader.KiltLoader.initMod(KiltLoader.kt:663)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//xyz.bluspring.kilt.loader.KiltLoader.initMods(KiltLoader.kt:620)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//xyz.bluspring.kilt.Kilt$Companion.load(Kilt.kt:206)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.kt:72)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.client.loading.ClientModLoader.lambda$begin$2(ClientModLoader.java:67)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:88)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:67)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.handler$boa000$kilt$initializeClientModLoader(class_310.java:3067)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.<init>(class_310.java:513)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.client.main.Main.main(Main.java:211)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:20:18] [Render thread/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: Config conflict detected!
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.fml.config.ConfigTracker.trackConfig(ConfigTracker.java:45)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:41)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:21)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//com.ldtteam.structurize.config.Configuration.<init>(Configuration.java:50)
[18:20:18] [Render thread/INFO]: [STDERR]: 	at knot//com.ldtteam.structurize.Structurize.<init>(Structurize.java:57)
[18:20:18] [Render thread/INFO]: [STDERR]: 	... 18 more
```

**Comment by Cartrigger** [comment]
https://mclo.gs/sBOc0d8

**Comment by mvsh258** [comment]
happened to me too

**Comment by Cartrigger** [comment]
https://mclo.gs/wIimk1s
Structurize now is completely borked

**Comment by Cartrigger** [comment]
https://mclo.gs/nCKq259

**Comment by Cartrigger** [comment]
https://mclo.gs/3mvaWfs
