### ISSUE TITLE
Crash with nothing

### ISSUE THREAD

**Issue by fireboy637** [BluSpring/Kilt#94]
### Version information

mc1.20.1+build.df826c

### Reproduction Steps

Install Kilt, launch Minecraft, and then crash.

### Java version

Java 17

### Crash Report file

[16:41:46] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.9
[16:41:46] [ForkJoinPool-1-worker-4/WARN]: Mod cpw_mods_securejarhandler uses the version fabric-2.1.6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[16:41:46] [main/INFO]: Loading 139 mods:
	- architectury 9.2.14
	- cloth-config 11.1.136
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	- forgeconfigapiport 8.0.1
	- java 17
	- kilt 0.0.1+mc1.20.1+build.df826c
	   |-- asmfabricloader 1.1.6
	   |    |-- net_fabricmc_tiny-mappings-parser 0.3.0+build.17
	   |    |-- net_lenni0451_classtransform_core 1.14.0
	   |    |-- net_lenni0451_reflect 1.4.0
	   |    \-- org_ow2_asm_asm-analysis 9.7
	   |-- com_github_thecatcore_cursedmixinextensions 1.1.0
	   |-- com_moulberry_mixinconstraints 1.0.1
	   |-- commons-codec_commons-codec 1.15
	   |-- cpw_mods_securejarhandler fabric-2.1.6
	   |-- mixinextras 0.5.0-beta.3
	   |-- mixinsquared 0.2.0-beta.6
	   |-- mm 2.3
	   |-- net_fabricmc_tiny-mappings-parser 0.3.0+build.17
	   |-- net_jodah_typetools 0.8.3
	   |-- net_minecraftforge_forgespi 7.1.3
	   |-- net_minecraftforge_mergetool-api 1.0
	   |-- net_minecraftforge_srgutils 0.4.13
	   |-- net_minecraftforge_unsafe 0.2.0
	   |-- net_minecrell_terminalconsoleappender 1.3.0
	   |-- noindium 1.1.0+1.20
	   |-- org_apache_maven_maven-artifact 3.8.5
	   |-- org_jline_jline-reader 3.12.1
	   |-- org_openjdk_nashorn_nashorn-core 15.4
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |-- porting_lib_asm 2.3.4+1.20.1
	   |-- porting_lib_attributes 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    |-- porting_lib_config 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_blocks 2.3.4+1.20.1
	   |-- porting_lib_brewing 2.3.4+1.20.1
	   |-- porting_lib_chunk_loading 2.3.4+1.20.1
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |-- porting_lib_common 2.3.4+1.20.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_data 2.3.4+1.20.1
	   |-- porting_lib_entity 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_fluids 2.3.4+1.20.1
	   |-- porting_lib_gametest 2.3.4+1.20.1
	   |-- porting_lib_gui_utils 2.3.4+1.20.1
	   |-- porting_lib_items 2.3.4+1.20.1
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |-- porting_lib_level_events 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |-- porting_lib_model_builders 2.3.4+1.20.1
	   |-- porting_lib_model_generators 2.3.4+1.20.1
	   |-- porting_lib_model_loader 2.3.4+1.20.1
	   |-- porting_lib_model_materials 2.3.4+1.20.1
	   |-- porting_lib_models 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |-- porting_lib_obj_loader 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   |-- porting_lib_registries 2.3.4+1.20.1
	   |-- porting_lib_tags 3.0
	   |-- porting_lib_tool_actions 2.3.4+1.20.1
	   |-- porting_lib_transfer 2.3.4+1.20.1
	   |-- porting_lib_utility 2.3.4+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   |-- team_reborn_energy 3.0.0
	   |-- xyz_bluspring_autorenamingtool 0.1.48
	   \-- xyz_bluspring_eventbus 6.2.12
	- minecraft 1.20.1
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
[16:41:47] [main/ERROR]: no good? no, this man is definitely up to evil.
[16:41:47] [main/INFO]: Scanning the mods directory for Forge mods...
[16:41:47] [main/INFO]: Found 0 Forge mods.
[16:41:47] [main/INFO]: No Forge mods located, not proceeding with mod remapping.
[16:41:48] [main/ERROR]: KnotClassLoader, you fool! You fell victim to one of the classic blunders!
[16:41:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/storage/emulated/0/FCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-
/
[16:41:49] [main/INFO]: Compatibility level set to JAVA_17
[16:41:50] [main/INFO]: Searching for graphics cards...
[16:41:50] [main/WARN]: Could not find any graphics adapters! Probably the device is not on a bus we can probe, or there are no devices supporting 3D acceleration.
[16:41:50] [main/WARN]: Unable to determine desktop session type because the environment variable XDG_SESSION_TYPE is not set! Your user session may not be configured correctly.
[16:41:50] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'kilt'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of xyz.bluspring.kilt.loader.KiltEarlyInitializer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: java.lang.NoClassDefFoundError: net/lenni0451/classtransform/InjectionCallback
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethod(Class.java:2673) ~[?:?]
	at com.llamalad7.mixinextras.utils.InternalMethod.of(InternalMethod.java:15) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.utils.InternalMethod.of(InternalMethod.java:44) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.utils.MixinInternals.<clinit>(MixinInternals.java:34) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.service.MixinExtrasServiceImpl.lambda$takeControlFrom$0(MixinExtrasServiceImpl.java:79) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at com.llamalad7.mixinextras.service.MixinExtrasServiceImpl.takeControlFrom(MixinExtrasServiceImpl.java:74) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.service.MixinExtrasService.setup(MixinExtrasService.java:33) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.MixinExtrasBootstrap.init(MixinExtrasBootstrap.java:20) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at xyz.bluspring.kilt.KiltMixinPlugin.onLoad(KiltMixinPlugin.java:33) ~[Kilt-0.0.1+mc1.20.1+build.df826c.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.lenni0451.classtransform.InjectionCallback
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethod(Class.java:2673) ~[?:?]
	at com.llamalad7.mixinextras.utils.InternalMethod.of(InternalMethod.java:15) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.utils.InternalMethod.of(InternalMethod.java:44) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.utils.MixinInternals.<clinit>(MixinInternals.java:34) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.service.MixinExtrasServiceImpl.lambda$takeControlFrom$0(MixinExtrasServiceImpl.java:79) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at com.llamalad7.mixinextras.service.MixinExtrasServiceImpl.takeControlFrom(MixinExtrasServiceImpl.java:74) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.service.MixinExtrasService.setup(MixinExtrasService.java:33) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at com.llamalad7.mixinextras.MixinExtrasBootstrap.init(MixinExtrasBootstrap.java:20) ~[mixinextras-0.5.0-beta.3-760be374baac5593.jar:?]
	at xyz.bluspring.kilt.KiltMixinPlugin.onLoad(KiltMixinPlugin.java:33) ~[Kilt-0.0.1+mc1.20.1+build.df826c.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more

### Additional information

Only the latest version of the required mods.

**Comment by teacat923** [comment]
Similarly, Kilt-0.0.1+mc1.20.1+build.a7ee85 crashed
or rather, it didn't start at all.
![image](https://github.com/user-attachments/assets/14c51ac1-bcbd-49d0-9e41-a3503c0b17d4)

This is the only thing I put in
